/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import conectar.conectar;
import static formularios.Clientes_mantenimiento.rnc;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan
 */
public class buscar_articulos extends javax.swing.JFrame {

    /**
     * Creates new form buscar_articulos
     */
    public buscar_articulos() {
        initComponents();
           cargar();
    }
    void cargar(){
        int Contador=0;
         DefaultTableModel modelo2 = (DefaultTableModel)tabla_art.getModel();
                  modelo2.setNumRows(0);

        String [] registros = new String [15];
        String sql ="SELECT * FROM articulo INNER JOIN proveedor on proveedor.idproveedor=articulo.id_proveedor INNER JOIN marca on marca.id_marca=articulo.id_marca where articulo.estado='existe' ";
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                Contador++;
                    registros[0] = rs.getString("cod_art");
                registros[1] = rs.getString("desc_art");
                registros[2] = rs.getString("cate_art");
                registros[3] = rs.getString("id_marca");
                registros[4] = rs.getString("no_marca");
                registros[5] = rs.getString("talla_art");
                registros[6]=rs.getString("cant_art");
                registros[7]=rs.getString("pre_compra");
                 registros[8] = rs.getString("pre_mayor");
                 registros[9] = rs.getString("pre_venta");
                 registros[10] = rs.getString("reorden");
                 registros[11] = rs.getString("id_proveedor");
                 registros[12]=rs.getString("representante");
                  registros[13]=rs.getString("itbis");
                 
                    String formato_fecha = rs.getString("fecha_art").split("-")[2]+"/"+rs.getString("fecha_art").split("-")[1]+"/"+rs.getString("fecha_art").split("-")[0];
               registros[14]=formato_fecha;
                
                modelo2.addRow(registros);
               
            }
            contador.setText(String.valueOf(Contador));
          tabla_art.setModel(modelo2);  
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buscar_articulo = new javax.swing.JTextField();
        contador = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_art = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setText("BUSCAR");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 30));

        buscar_articulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buscar_articulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscar_articuloMouseClicked(evt);
            }
        });
        buscar_articulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscar_articuloKeyReleased(evt);
            }
        });
        jPanel2.add(buscar_articulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 737, 30));

        contador.setBackground(new java.awt.Color(0, 0, 0));
        contador.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        contador.setForeground(new java.awt.Color(255, 0, 0));
        contador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contadorActionPerformed(evt);
            }
        });
        jPanel2.add(contador, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 70, 100, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("REGISTRO");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 70, 80, 33));

        tabla_art.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tabla_art.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descripcion", "Categoria", "ID", "Marca", "Talla", "Cantidad", "Compra", "P.Mayor", "Consumidor", "Reorden", "ID", "Proveedor", "Itbis", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_art.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_artMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabla_art);
        if (tabla_art.getColumnModel().getColumnCount() > 0) {
            tabla_art.getColumnModel().getColumn(14).setMinWidth(100);
            tabla_art.getColumnModel().getColumn(14).setMaxWidth(100);
        }

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 101, 1040, 268));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\Proyecto duany\\proyectoVentaO-M\\src\\iconos\\centro-comercial.png")); // NOI18N
        jLabel3.setText("Articulos  Registrados");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 260, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscar_articuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscar_articuloMouseClicked
        buscar_articulo.setText("");
    }//GEN-LAST:event_buscar_articuloMouseClicked

    private void buscar_articuloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscar_articuloKeyReleased
        filtrar(buscar_articulo.getText());
    }//GEN-LAST:event_buscar_articuloKeyReleased
   
    void filtrar(String valor){
         DefaultTableModel modelo2 = (DefaultTableModel)tabla_art.getModel();
             modelo2.setNumRows(0);
        String [] registros = new String [15];
        String sql ="SELECT * FROM articulo INNER JOIN proveedor on proveedor.idproveedor=articulo.id_proveedor INNER JOIN marca on marca.id_marca=articulo.id_marca where  articulo.estado='existe' and CONCAT (cod_art,'',desc_art,'',no_marca,'',cate_art)LIKE '%"+valor+"%'";
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                    registros[0] = rs.getString("cod_art");
                registros[1] = rs.getString("desc_art");
                registros[2] = rs.getString("cate_art");
                registros[3] = rs.getString("id_marca");
                registros[4] = rs.getString("no_marca");
                registros[5] = rs.getString("talla_art");
                registros[6]=rs.getString("cant_art");
                registros[7]=rs.getString("pre_compra");
                 registros[8] = rs.getString("pre_mayor");
                 registros[9] = rs.getString("pre_venta");
                 registros[10] = rs.getString("reorden");
                 registros[11] = rs.getString("id_proveedor");
                 registros[12]=rs.getString("representante");
                  registros[13]=rs.getString("itbis");
                 
                    String formato_fecha = rs.getString("fecha_art").split("-")[2]+"/"+rs.getString("fecha_art").split("-")[1]+"/"+rs.getString("fecha_art").split("-")[0];
               registros[14]=formato_fecha;
                
                
                modelo2.addRow(registros);
               
            }
          tabla_art.setModel(modelo2);  
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    private void tabla_artMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_artMouseClicked

            int fila = tabla_art.getSelectedRow();
            if (fila>=0){
                crear_articulo.id_art.setText(tabla_art.getValueAt(fila, 0).toString());
                crear_articulo.des_art.setText(tabla_art.getValueAt(fila, 1).toString());
                crear_articulo.categoria.setSelectedItem(tabla_art.getValueAt(fila, 2).toString());
                crear_articulo.id_marca.setText(tabla_art.getValueAt(fila, 3).toString());
                crear_articulo.talla.setText(tabla_art.getValueAt(fila, 5).toString());
                crear_articulo.cant.setText(tabla_art.getValueAt(fila, 6).toString());
                crear_articulo.pre_com.setText(tabla_art.getValueAt(fila, 7).toString());
                crear_articulo.pre_mayor.setText(tabla_art.getValueAt(fila, 8).toString());
                crear_articulo.pre_consumidor.setText(tabla_art.getValueAt(fila, 9).toString());
                crear_articulo.reorden.setText(tabla_art.getValueAt(fila, 10).toString());
                crear_articulo.id_proveedor.setText(tabla_art.getValueAt(fila, 11).toString());
                crear_articulo.itbis.setText(tabla_art.getValueAt(fila, 13).toString());

                Date fecha = new Date(tabla_art.getValueAt(fila, 14).toString().split("/")[1]+"/"+tabla_art.getValueAt(fila, 14).toString().split("/")[2]+"/"+tabla_art.getValueAt(fila, 14).toString().split("/")[0]);
                crear_articulo.txt_fecha.setDate(fecha);
                
                 crear_articulo.id = crear_articulo.id_art.getText();
            crear_articulo.des_art.requestFocus();
            crear_articulo.cant.setEnabled(false);
                 this.dispose();
            }
           

    }//GEN-LAST:event_tabla_artMouseClicked

    private void contadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buscar_articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buscar_articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buscar_articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buscar_articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buscar_articulos().setVisible(true);
            }
        });
    }
conectar con = new conectar();
      Connection cn = con.connection();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscar_articulo;
    private javax.swing.JTextField contador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla_art;
    // End of variables declaration//GEN-END:variables
}
