/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.carga_tab_permisos_usuarios;
import conectar.conectar;
import java.awt.Color;
import java.awt.Font;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/**
 *
 * @author Lenovo
 */
public class buscarUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form buscarUsuarios
     */
    public buscarUsuarios() {
        initComponents();
        sql_usuario = new clases.sql_usuario();
        cargar();
        dtm = new DefaultTableModel();

    }

    void cargar() {
        DefaultTableModel modelo2 = (DefaultTableModel) tabla_usu.getModel();
        modelo2.getDataVector().clear();
        String[] registros = new String[9];
        String sql = "SELECT * FROM registro_usuario ";
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("idempleado");
                registros[1] = rs.getString("idempleado");
                registros[2] = rs.getString("nombre");
                registros[3] = rs.getString("usuario");
                registros[4] = rs.getString("tipo");

                modelo2.addRow(registros);

            }
            tabla_usu.setModel(modelo2);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    public void carga_tabla_permiso_roles_usu(int id_usuario) {

        TableModel tm = Registro_usuarios.jtable_permiso.getModel();
        dtm = (DefaultTableModel) tm;
        dtm.setRowCount(0);
        //int id_usuario = Integer.parseInt(jframe_usuario.txtidusuario.getText());
        Object datos[] = sql_usuario.busca_permiso_roles_usu(id_usuario);
        rs = (ResultSet) datos[0];
        try {

            Object[] filas = new Object[8];
            while (rs.next()) {
                filas[0] = rs.getString("P.aplicaciones_modulos");
                filas[1] = rs.getBoolean("R.acceso");
                filas[2] = rs.getBoolean("R.crear");
                filas[3] = rs.getBoolean("R.modificar");
                filas[4] = rs.getBoolean("R.borrar");
                filas[5] = rs.getBoolean("R.anular");
                filas[6] = rs.getBoolean("R.imprimir");
                filas[7] = rs.getBoolean("R.exportar");
                dtm.addRow(filas);
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            Connection con = (Connection) datos[2];
            CallableStatement enlaza_bbdd = (CallableStatement) datos[1];
            try {
                rs.close();
            } catch (Exception e) {
                e.printStackTrace();

            }
            try {
                enlaza_bbdd.close();
            } catch (Exception e) {
                e.printStackTrace();

            }
            try {
                con.close();
            } catch (Exception e) {
                e.printStackTrace();

            }
        }

    }

    void filtrar(String valor) {
        DefaultTableModel modelo2 = (DefaultTableModel) tabla_usu.getModel();
        modelo2.getDataVector().clear();
        String[] registros = new String[9];
        String sql = "SELECT * FROM registro_usuario  where CONCAT (idempleado,'',nombre)LIKE '%" + valor + "%' ";
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("idempleado");
                registros[1] = rs.getString("idempleado");
                registros[2] = rs.getString("nombre");
                registros[3] = rs.getString("usuario");
                registros[4] = rs.getString("tipo");

                modelo2.addRow(registros);

            }
            tabla_usu.setModel(modelo2);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        buscar_usuario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_usu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\Proyecto duany\\proyectoVentaO-M\\src\\iconos\\lupa.png")); // NOI18N
        jLabel6.setText("BUSCAR");

        buscar_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buscar_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscar_usuarioKeyReleased(evt);
            }
        });

        tabla_usu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabla_usu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID EMP.", "ID", "NOMBRE", "USUARIO", "CARGO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_usu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_usuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabla_usuMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_usu);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscar_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscar_usuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscar_usuarioKeyReleased
        filtrar(buscar_usuario.getText());
    }//GEN-LAST:event_buscar_usuarioKeyReleased

    private void tabla_usuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_usuMouseClicked
        int fila = tabla_usu.getSelectedRow();
        if (fila >= 0) {
            Registro_usuarios.idempleado.setText(tabla_usu.getValueAt(fila, 0).toString());
            Registro_usuarios.nombre.setText(tabla_usu.getValueAt(fila, 2).toString());
            Registro_usuarios.usuario.setText(tabla_usu.getValueAt(fila, 3).toString());
            Registro_usuarios.jComboBox1.setSelectedItem(tabla_usu.getValueAt(fila, 4).toString());
            carga_tabla_permiso_roles_usu(Integer.parseInt(tabla_usu.getValueAt(fila, 0).toString()));
             this.dispose();
        }

    }//GEN-LAST:event_tabla_usuMouseClicked

    private void tabla_usuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_usuMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tabla_usuMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buscarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buscarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buscarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buscarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buscarUsuarios().setVisible(true);
            }
        });
    }

    // private carga_tab_permisos_usuarios tabla_permisos;
    //private formularios.Registro_usuarios WindowsRegistro_usuarios;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscar_usuario;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tabla_usu;
    // End of variables declaration//GEN-END:variables

    conectar con = new conectar();
    Connection cn = con.connection();
    private clases.sql_usuario sql_usuario;
    private ResultSet rs;
    DefaultTableModel dtm;
}
