/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formularios;

import conectar.conectar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class marca extends javax.swing.JFrame {

    /** Creates new form marca */
    public marca() {
        initComponents();
        cargar();
        numero_serie();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_marca = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        buscar_marca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        contador_txt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        guardar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTRO DE MARCAS");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\proyecto\\Proyecto duany\\src\\iconos\\bolso.png")); // NOI18N
        jLabel1.setText("REGISTRO DE MARCAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 180, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("CODIGO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 70, 60, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("NOMBRE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 80, 70, 20));

        codigo.setEditable(false);
        codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoActionPerformed(evt);
            }
        });
        jPanel1.add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 78, 190, 25));
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 78, 280, 25));

        tabla_marca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_marca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_marcaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_marca);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 680, 170));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Downloads\\lupa.png")); // NOI18N
        jLabel4.setText("BUSCAR");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 90, 30));

        buscar_marca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscar_marcaKeyReleased(evt);
            }
        });
        jPanel1.add(buscar_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 440, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("REGISTROS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, 30));

        contador_txt.setBackground(new java.awt.Color(0, 0, 0));
        contador_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contador_txt.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(contador_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 80, 30));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        guardar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        guardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\proyecto\\Proyecto duany\\src\\iconos\\salvar.png")); // NOI18N
        guardar.setText("Guardar");
        guardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        guardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                guardarKeyPressed(evt);
            }
        });
        jPanel3.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 10, 100, 40));

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\proyecto\\Proyecto duany\\src\\iconos\\actualizar.png")); // NOI18N
        jButton4.setText("Modificar");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 127, 40));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\proyecto\\Proyecto duany\\src\\iconos\\cruzar.png")); // NOI18N
        jButton2.setText("Eliminar");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 118, 40));

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\proyecto\\Proyecto duany\\src\\iconos\\anadir (1).png")); // NOI18N
        jButton6.setText("Nuevo");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 116, 40));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\proyecto\\Proyecto duany\\src\\iconos\\salida.png")); // NOI18N
        jButton1.setText("Salir");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 106, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 680, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void guardar(){
   
  
       try {
           String sql125= "";
           sql125 = "INSERT INTO marca (no_marca) VALUES('"+nombre.getText()+"')";
           
           PreparedStatement psk22 = cn.prepareStatement(sql125);
           
             int n ;
             n = psk22.executeUpdate();
             if (n > 0){
                 JOptionPane.showMessageDialog(null, "DATOS REGISTRADOS CON EXITO");
             }
       } catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex);
           JOptionPane.showMessageDialog(null, "ERROR EN GUARDAR DATOS ","NO SE PUEDE REGISTRAR",JOptionPane.ERROR_MESSAGE);
       }
   }
    
     void reiniciarJTable(javax.swing.JTable Tabla){
        DefaultTableModel modelo = (DefaultTableModel) tabla_marca.getModel();
        modelo.setNumRows(0);
    }
    void limpiar(){
       nombre.setText("");
       numero_serie();
    }
    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
       if (nombre.getText().equals("")){
            JOptionPane.showMessageDialog(null,"EL NOMBRE ESTA EN BLANCO");
            nombre.requestFocus();
            return;
        }

        guardar();
        reiniciarJTable(tabla_marca);
        cargar();
        actualizar_codigo();
                limpiar();

        //this.dispose();
        //crear_articulo windows = new crear_articulo();
        //windows.setVisible(true);
        //windows.setLocationRelativeTo(null);
    }//GEN-LAST:event_guardarActionPerformed
     void actualizar_codigo() {
       
            try {
                PreparedStatement psU = cn.prepareStatement("UPDATE contador SET idmarca=idmarca + 1  " );
                psU.executeUpdate();
                // JOptionPane.showMessageDialog(null, "DATOS MODIFICADOS CON EXITO");
            } catch (Exception ex) {
                Logger.getLogger(empleado_1.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        codigo.requestFocus();
    }
    
    void cargar(){
    int contador=0;
       DefaultTableModel modelo2 = (DefaultTableModel)tabla_marca.getModel();
    modelo2.setNumRows(0);
        String [] registros = new String [2];
        String sql ="SELECT * FROM marca where estado='existe'";
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                contador++;
                registros[0]=rs.getString("id_marca");
                registros[1]=rs.getString("no_marca");
               modelo2.addRow(registros);
             
            }
          tabla_marca.setModel(modelo2); 
          contador_txt.setText(String.valueOf(contador));
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    void numero_serie() {
        String[] registros = new String[6];
        String sql = "SELECT idmarca FROM contador ";
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("idmarca");

            }
            int numero_serie = Integer.parseInt(registros[0]);
            numero_serie = numero_serie + 1;
            codigo.setText(String.valueOf( numero_serie));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    private void guardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_guardarKeyPressed
       /* if(evt.getKeyCode()==KeyEvent.VK_ENTER){

            guardar();
            cargar();
            limpiar();
            actualizar_codigo();
            this.dispose();
            crear_articulo windows = new crear_articulo();
            windows.setVisible(true);
            windows.setLocationRelativeTo(null);

        }*/
    }//GEN-LAST:event_guardarKeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 if (nombre.getText().equals("")){
            JOptionPane.showMessageDialog(null,"DEBE INGRESAR EL NOMBRE");
            nombre.requestFocus();
            return;             
        }
        
  try {
            PreparedStatement psU = cn.prepareStatement("UPDATE marca SET no_marca='"+nombre.getText()+"'  where id_marca='"+codigo.getText()+"'");
                
            psU.executeUpdate();
            JOptionPane.showMessageDialog(null, "DATOS MODIFICADOS CON EXITO");
        } catch (Exception ex) {
            Logger.getLogger(crear_articulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        cargar();
        limpiar();
    }//GEN-LAST:event_jButton4ActionPerformed
void filtrar(String valor){
         DefaultTableModel modelo2 = (DefaultTableModel)tabla_marca.getModel();
         modelo2.setNumRows(0);
        String [] registros = new String [2];
        String sql ="SELECT * FROM marca  where estado='existe' and CONCAT (id_marca,'',no_marca)LIKE '%"+valor+"%' ";
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
               registros[0]=rs.getString("id_marca");
                registros[1]=rs.getString("no_marca");
               
                
                
                modelo2.addRow(registros);
               
            }
          tabla_marca.setModel(modelo2);  
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
        
}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if (nombre.getText().equals("")){
            JOptionPane.showMessageDialog(null,"DEBE INGRESAR EL NOMBRE");
            nombre.requestFocus();
            return;             
        }
        
  try {
            PreparedStatement psU = cn.prepareStatement("UPDATE marca SET estado='no_existe'  where id_marca='"+codigo.getText()+"'");
                
            psU.executeUpdate();
            JOptionPane.showMessageDialog(null, "DATOS MODIFICADOS CON EXITO");
        } catch (Exception ex) {
            Logger.getLogger(crear_articulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        cargar();
        limpiar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        limpiar();
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabla_marcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_marcaMouseClicked
       int fila = tabla_marca.getSelectedRow();
        if (fila>=0){
            codigo.setText(tabla_marca.getValueAt(fila, 0).toString());
           nombre.setText(tabla_marca.getValueAt(fila, 1).toString());

        }
        
        id = codigo.getText();
        nombre.requestFocus();  
        crear_articulo.id_marca.setText(codigo.getText());
    }//GEN-LAST:event_tabla_marcaMouseClicked

    private void buscar_marcaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscar_marcaKeyReleased
                filtrar(buscar_marca.getText());        

    }//GEN-LAST:event_buscar_marcaKeyReleased

    private void codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(marca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(marca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(marca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(marca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new marca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscar_marca;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField contador_txt;
    private javax.swing.JButton guardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTable tabla_marca;
    // End of variables declaration//GEN-END:variables
String id="";
    
    conectar con = new conectar();
      Connection cn = con.connection();
}
